# Generated by Django 5.2.17 on 2026-10-03 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(default='emma', max_length=50)),
                ('source_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_analytics', models.BooleanField(default=True)),
                ('include_in_no_spend_tracking', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'display_name', 'source_name'],
            },
        ),
        migrations.CreateModel(
            name='RewardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('streak', 'No-spend streak'), ('monthly_count', 'Monthly no-spend days'), ('personal_record', 'Personal record')], max_length=30)),
                ('threshold', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EarnedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_rewards', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_rewards', to='finance.rewarddefinition')),
            ],
            options={
                'ordering': ['-earned_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpendRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rule_scope', models.CharField(choices=[('spend', 'Spend'), ('no_spend', 'No-spend day'), ('both', 'Both')], default='both', max_length=20)),
                ('match_field', models.CharField(choices=[('account', 'Account'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('type', 'Type'), ('merchant', 'Merchant'), ('counterparty', 'Counterparty')], max_length=20)),
                ('match_operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('starts_with', 'Starts with')], default='equals', max_length=20)),
                ('match_value', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('include_spend', 'Include in spend'), ('exclude_spend', 'Exclude from spend'), ('include_no_spend', 'Include against no-spend day'), ('exclude_no_spend', 'Exclude from no-spend day')], max_length=30)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(default='emma', max_length=50)),
                ('source_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('source_category', models.CharField(blank=True, max_length=255)),
                ('source_subcategory', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_tags', models.TextField(blank=True)),
                ('source_counterparty', models.CharField(blank=True, max_length=255)),
                ('source_custom_name', models.CharField(blank=True, max_length=255)),
                ('source_merchant', models.CharField(blank=True, max_length=255)),
                ('source_additional_details', models.TextField(blank=True)),
                ('source_notes', models.TextField(blank=True)),
                ('source_linked_transaction_id', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_source_sync_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('qualifying_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('qualifying_transaction_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_no_spend_day', models.BooleanField(blank=True, null=True)),
                ('calculation_version', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_status_user_date')],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'is_active'], name='finance_fin_user_id_e211f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'source_system', 'source_name', 'institution_name'), name='uniq_account_user_source_name_institution'),
        ),
        migrations.AddIndex(
            model_name='spendrule',
            index=models.Index(fields=['user', 'is_active', 'priority'], name='finance_spe_user_id_f541ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='finance_tra_user_id_bed389_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_date'], name='finance_tra_account_6fd188_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'source_category', 'transaction_date'], name='finance_tra_user_id_62465a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_transaction_id__isnull', False), models.Q(('source_transaction_id', ''), _negated=True)), fields=('user', 'source_system', 'source_transaction_id'), name='uniq_transaction_user_source_external_id'),
        ),
    ]
