# Generated by Django 5.2.17 on 2026-10-03 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='emma', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emma import',
                'verbose_name_plural': 'Emma imports',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmmaRawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(default='emma', max_length=50)),
                ('source_transaction_id', models.CharField(max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emma_raw_transactions', to=settings.AUTH_USER_MODEL)),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_transactions', to='finance.importrun')),
            ],
            options={
                'verbose_name': 'Emma raw transaction',
                'verbose_name_plural': 'Emma raw transactions',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'source_row_number'], name='finance_emm_user_id_45ff37_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_system', 'source_transaction_id'), name='uniq_emma_raw_user_source_id')],
            },
        ),
    ]
