# Generated by Django 5.2.17 on 2026-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_description_transaction_merchant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
