# Generated by Django 5.2.17 on 2026-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_source_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='error_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='job_type',
            field=models.CharField(choices=[('intraday', 'Intraday'), ('daily', 'Daily rolling'), ('full', 'Full reconciliation'), ('manual', 'Manual range')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='importrun',
            name='requested_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='requested_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='transactions_missing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='transactions_restored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='transactions_unchanged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='trigger_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('manual_cli', 'Manual CLI')], default='manual_cli', max_length=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_state',
            field=models.CharField(choices=[('active', 'Active'), ('missing', 'Missing')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=10),
        ),
    ]
