# Generated by Django 5.2.17 on 2026-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_importrun_duration_ms_importrun_error_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='transactions_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='transactions_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
